#!/usr/bin/env python3
"""Regenerate or verify Owl Docs' checked-in hicolor application icons."""

from __future__ import annotations

import argparse
import hashlib
import io
from pathlib import Path
import sys
import zlib

import PIL
from PIL import Image


SIZES = (16, 24, 32, 48, 64, 128, 256, 512)
MASTER_SHA256 = "058f151ffce9299c30d8cc068d17f21b4b5c34f3701b6b76641a1fa2f58c6205"
MASTER_SIZE = (1254, 1254)
REQUIRED_PILLOW_VERSION = "12.3.0"
REQUIRED_ZLIB_VERSION = "1.3.2"

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
ICON_ROOT = REPOSITORY_ROOT / "packaging" / "icons"
MASTER_PATH = ICON_ROOT / "owl-docs-master.png"


def output_path(size: int) -> Path:
    return ICON_ROOT / "hicolor" / f"{size}x{size}" / "apps" / "owl-docs.png"


def check_runtime() -> None:
    if PIL.__version__ != REQUIRED_PILLOW_VERSION:
        raise RuntimeError(
            f"Pillow {REQUIRED_PILLOW_VERSION} is required; found {PIL.__version__}"
        )
    if zlib.ZLIB_RUNTIME_VERSION != REQUIRED_ZLIB_VERSION:
        raise RuntimeError(
            f"zlib {REQUIRED_ZLIB_VERSION} is required; "
            f"found {zlib.ZLIB_RUNTIME_VERSION}"
        )


def load_master() -> Image.Image:
    encoded = MASTER_PATH.read_bytes()
    digest = hashlib.sha256(encoded).hexdigest()
    if digest != MASTER_SHA256:
        raise RuntimeError(
            "canonical icon hash changed; review and update provenance intentionally"
        )
    with Image.open(io.BytesIO(encoded)) as source:
        if source.size != MASTER_SIZE or source.mode != "RGBA":
            raise RuntimeError("canonical icon must remain a 1254 x 1254 RGBA PNG")
        return source.copy()


def render_png(master: Image.Image, size: int) -> bytes:
    premultiplied = master.convert("RGBa")
    resized = premultiplied.resize(
        (size, size), Image.Resampling.LANCZOS, reducing_gap=3.0
    ).convert("RGBA")
    encoded = io.BytesIO()
    resized.save(encoded, format="PNG", optimize=True, compress_level=9)
    return encoded.getvalue()


def verify(master: Image.Image) -> bool:
    expected_paths = {output_path(size) for size in SIZES}
    actual_paths = set(ICON_ROOT.glob("hicolor/*x*/apps/owl-docs.png"))
    success = True
    if actual_paths != expected_paths:
        missing = sorted(expected_paths - actual_paths)
        unexpected = sorted(actual_paths - expected_paths)
        for path in missing:
            print(f"missing generated icon: {path.relative_to(REPOSITORY_ROOT)}")
        for path in unexpected:
            print(f"unexpected generated icon: {path.relative_to(REPOSITORY_ROOT)}")
        success = False

    for size in SIZES:
        path = output_path(size)
        generated = render_png(master, size)
        if not path.is_file() or path.read_bytes() != generated:
            print(f"generated bytes differ: {path.relative_to(REPOSITORY_ROOT)}")
            success = False
    return success


def write(master: Image.Image) -> None:
    for size in SIZES:
        path = output_path(size)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(render_png(master, size))
        print(f"wrote {path.relative_to(REPOSITORY_ROOT)}")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check", action="store_true", help="verify checked-in assets byte for byte"
    )
    mode.add_argument("--write", action="store_true", help="regenerate checked-in assets")
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    try:
        check_runtime()
        master = load_master()
        if arguments.check:
            if not verify(master):
                return 1
            print("all Owl Docs application icons match the canonical master")
        else:
            write(master)
    except (OSError, RuntimeError) as error:
        print(f"icon generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
